export const products = [
  { id: 1, name: 'Aero Luxe 3-in-1 Travel System', category: 'Travel Systems', price: 8999, tag: 'BESTSELLER', tone: 'sand', image: 'https://lorelli.eu/storage/products/1002201/bianca-3in1-beige.jpg', description: 'Premium pram, carry cot and infant car seat combination with an aluminium frame and one-hand fold.' },
  { id: 2, name: 'Signature 5-in-1 Travel System', category: 'Travel Systems', price: 18999, tag: 'LUXE', tone: 'stone', image: 'https://lamborghinistroller.com/images/product-sian-gold.png', description: 'A statement travel system with reversible seat, carry cot, car seat, base and premium accessories.' },
  { id: 3, name: 'Orbit 360° ISOFIX Car Seat', category: 'Car Seats', price: 6999, tag: 'i-SIZE', tone: 'charcoal', image: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=900&q=85', description: '360-degree rotating ISOFIX seat with newborn insert, side-impact protection and multiple recline positions.' },
  { id: 4, name: 'Executive i-Size Car Seat', category: 'Car Seats', price: 12499, tag: 'PREMIUM', tone: 'ink', image: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?auto=format&fit=crop&w=900&q=85', description: 'Extended-use premium car seat with advanced impact protection, ventilated shell and luxury fabrics.' },
  { id: 5, name: 'Metro Compact Stroller', category: 'Strollers', price: 4999, tag: 'TRAVEL', tone: 'sage', image: 'https://lamborghinistroller.com/images/product-sian-gold.png', description: 'Lightweight compact stroller made for airports, city trips and easy boot storage.' },
  { id: 6, name: 'Terrain Pro All-Road Pram', category: 'Strollers', price: 11999, tag: 'ALL-TERRAIN', tone: 'olive', image: 'https://lorelli.eu/storage/products/1002201/bianca-3in1-beige.jpg', description: 'Large wheels, smooth suspension and an extendable canopy for comfortable family adventures.' },
  { id: 7, name: 'Oak Convertible Cot Bed', category: 'Nursery', price: 7499, tag: 'NEW', tone: 'oak', image: 'https://www.centraledesmultiples.com/img_product/v/o/1000/vo061606036_2.jpg', description: 'A refined cot that converts into a toddler bed, finished in a warm contemporary wood look.' },
  { id: 8, name: 'Cloud Electric Baby Swing', category: 'Nursery', price: 3499, tag: 'SMART', tone: 'cream', image: 'https://images.unsplash.com/photo-1617331140180-e8262094733a?auto=format&fit=crop&w=900&q=85', description: 'Quiet electric swing with soothing motion modes, timer controls and plush newborn support.' },
  { id: 9, name: 'ViewPro Smart Baby Monitor', category: 'Baby Tech', price: 2999, tag: 'HD VIDEO', tone: 'blue', image: 'https://m.media-amazon.com/images/I/71eOQTKbWVL._AC_SL1500_.jpg', description: 'HD video monitoring with night vision, two-way audio and room-temperature alerts.' },
  { id: 10, name: 'Maison Premium High Chair', category: 'Feeding Furniture', price: 3899, tag: 'DESIGN', tone: 'latte', image: 'https://images.unsplash.com/photo-1599443015574-be5fe8a05783?auto=format&fit=crop&w=900&q=85', description: 'Easy-clean premium high chair with adjustable footrest, removable tray and modern dining-room styling.' },
  { id: 11, name: 'Aura Ergonomic Baby Carrier', category: 'On The Go', price: 2499, tag: 'ERGONOMIC', tone: 'clay', image: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=900&q=85', description: 'Structured carrier with breathable panels, lumbar support and multiple comfortable carry positions.' },
  { id: 12, name: 'Nurture Nursery Rocking Chair', category: 'Nursery', price: 6499, tag: 'COMFORT', tone: 'mushroom', image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85', description: 'Deeply cushioned rocking chair designed for feeding, soothing and slow nursery moments.' },
]

export const categories = ['All', 'Travel Systems', 'Car Seats', 'Strollers', 'Nursery', 'Baby Tech', 'Feeding Furniture', 'On The Go']
