const pics = {
  pram: 'https://www.chelino.co.za/cdn/shop/files/Nuna_TRVLlx_BMW_Mica_Angle_CD_GL_web.png?v=1773043551&width=1096',
  pram2: 'https://www.chelino.co.za/cdn/shop/files/Lunar_Signature_Coffee_Stroller_1.jpg?v=1777466092&width=1096',
  pram3: 'https://www.chelino.co.za/cdn/shop/files/Lunar_Signature_Black_Stroller_1.jpg?v=1779109465&width=1096',
  carseat: 'https://carseatninja.com/cdn/shop/products/DUALFIX_M_PLUS_SpaceBlack_02_2022_72dpi_2000x2000_d3debed8-2bee-444e-943a-345c19b7c9f2.png?v=1667854437&width=1946',
  carseat2: 'https://www.mamasandpapas.com/cdn/shop/products/maxi-cosi-baby-car-seats-maxi-cosi-pearl-360-pro-car-seat-in-black-34290943262885_1200x1200.jpg?v=1733906407',
  cot: 'https://www.babyelegance.com/cdn/shop/files/043024_BabyElegance_Store5609.jpg?v=1714643233&width=1500',
  swing: 'https://uk.momcozy.com/cdn/shop/files/1.0.png?v=1757318953&width=600',
  monitor: 'https://cdn-web.vtp-media.com/products/VM/VM320/VM320_combo_L3Q.jpg',
  steriliser: 'https://i5.walmartimages.com/asr/5f47338e-11a4-412d-88cc-975670683ae9.e34aa5d3f800fa024243f9b73597a082.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768',
  highchair: 'https://mamasandpapas.ae/on/demandware.static/-/Sites-MnP-master-catalog/default/dw4112c48b/sfcc-mnp-production/2/1/9/2/4/219245963_FR.jpg',
  carrier: 'https://babybeeonline.com/cdn/shop/files/BBAU_2025_WEBSITE_JOEY_PRODUCTMAINCAROUSEL_316f29f0-e8b0-4628-bd7f-4c4d1c2b7a76.png?v=1752470194&width=1200'
}

const p = (id, name, category, price, tag, image, description) => ({ id, name, category, price, tag, image, description })

export const products = [
  p(1,'Aero Luxe 3-in-1 Travel System','Prams & Travel Systems',8999,'BESTSELLER',pics.pram,'Premium pram, carry cot and infant car seat combination with an aluminium frame and one-hand fold.'),
  p(2,'Signature 5-in-1 Travel System','Prams & Travel Systems',18999,'PREMIUM',pics.pram2,'Reversible seat, carry cot, infant car seat, base and premium accessories.'),
  p(3,'Metro Compact Pram','Prams & Travel Systems',4999,'COMPACT',pics.pram3,'Lightweight compact pram made for airports, city trips and easy boot storage.'),
  p(4,'Terrain Pro All-Road Pram','Prams & Travel Systems',11999,'ALL-TERRAIN',pics.pram2,'Large wheels, smooth suspension and an extendable canopy for family adventures.'),
  p(5,'Urban Fold Stroller','Prams & Travel Systems',6499,'CITY',pics.pram3,'One-hand folding city stroller with a spacious basket and full recline.'),
  p(6,'Nova Twin Pram','Prams & Travel Systems',13999,'TWIN',pics.pram2,'Premium double pram with independent reclining seats and generous storage.'),
  p(7,'Voyager 4-in-1 Travel Set','Prams & Travel Systems',14999,'TRAVEL',pics.pram,'Complete newborn-to-toddler travel set with adaptable seating configurations.'),
  p(8,'Mini Air Cabin Stroller','Prams & Travel Systems',5799,'CABIN',pics.pram3,'Ultra-compact travel stroller designed for quick trips and cabin-friendly portability.'),
  p(9,'Summit Luxe Pram','Prams & Travel Systems',15999,'LUXE',pics.pram2,'Luxury pram with premium fabrics, large canopy and smooth suspension.'),
  p(10,'Everyday Flex Travel System','Prams & Travel Systems',9999,'FAMILY',pics.pram,'Versatile travel system designed for daily errands, naps and longer outings.'),

  p(11,'Orbit 360° ISOFIX Car Seat','Car Seats',6999,'i-SIZE',pics.carseat,'360-degree rotating ISOFIX seat with newborn insert and side-impact protection.'),
  p(12,'Executive i-Size Car Seat','Car Seats',12499,'PREMIUM',pics.carseat2,'Extended-use premium seat with advanced impact protection and luxury fabrics.'),
  p(13,'SafeNest Infant Carrier','Car Seats',3999,'NEWBORN',pics.carseat,'Lightweight infant carrier with padded newborn support and secure installation.'),
  p(14,'Guardian Pro 360 Seat','Car Seats',8499,'360°',pics.carseat2,'Rotating seat with multiple recline positions and extended rear-facing use.'),
  p(15,'Journey Grow Car Seat','Car Seats',5499,'GROW',pics.carseat2,'Multi-stage seat designed to adapt from toddler years into childhood.'),
  p(16,'CloudRide Infant Seat','Car Seats',4599,'LIGHT',pics.carseat,'Comfort-focused infant seat with ergonomic carry handle and canopy.'),
  p(17,'Fortress i-Size Plus','Car Seats',9999,'SAFETY',pics.carseat2,'Premium i-Size protection with reinforced side wings and adjustable headrest.'),
  p(18,'CitySafe ISOFIX Seat','Car Seats',5999,'ISOFIX',pics.carseat2,'Compact ISOFIX car seat ideal for everyday urban family travel.'),
  p(19,'Elite 360 Signature','Car Seats',13999,'LUXE',pics.carseat2,'Flagship rotating seat combining premium materials with advanced safety features.'),
  p(20,'Junior Flex Booster','Car Seats',3299,'BOOSTER',pics.carseat2,'High-back booster with adjustable side protection and comfortable padding.'),

  p(21,'Serenity Convertible Cot','Nursery',7999,'NURSERY',pics.cot,'Modern convertible cot with adjustable mattress heights and timeless neutral finish.'),
  p(22,'Cloud Electric Baby Swing','Nursery',3499,'SMART',pics.swing,'Quiet electric swing with soothing motion modes and plush newborn support.'),
  p(23,'Oakline Cot Bed','Nursery',9499,'PREMIUM',pics.cot,'Warm wood-look cot that converts into a stylish toddler bed.'),
  p(24,'DreamNest Bassinet','Nursery',4299,'NEWBORN',pics.cot,'Bedside bassinet with breathable sides and a comfortable newborn sleep space.'),
  p(25,'Nurture Rocking Chair','Nursery',6499,'COMFORT',pics.cot,'Deeply cushioned nursery chair for feeding, soothing and bedtime routines.'),
  p(26,'Willow Changing Station','Nursery',5999,'STORAGE',pics.cot,'Premium changing unit with generous drawers and a removable changing top.'),
  p(27,'Little Haven Wardrobe','Nursery',10999,'FURNITURE',pics.cot,'Full-size nursery wardrobe with hanging space, shelves and soft-close doors.'),
  p(28,'Moonlight Cradle','Nursery',4999,'CRADLE',pics.cot,'Compact rocking cradle with a soft neutral finish for early months.'),
  p(29,'Serenity Cot & Drawer Set','Nursery',12499,'SET',pics.cot,'Coordinated cot and storage set for a polished nursery setup.'),
  p(30,'Nest Ottoman & Rocker Set','Nursery',8499,'LUXE',pics.cot,'Comfortable feeding chair and matching footrest for long nursery sessions.'),

  p(31,'ViewPro Smart Baby Monitor','Baby Tech',2999,'HD VIDEO',pics.monitor,'HD video monitoring with night vision, two-way audio and temperature alerts.'),
  p(32,'PureSteam Bottle Steriliser','Baby Tech',1899,'HYGIENE',pics.steriliser,'Fast steam sterilising with spacious capacity and one-touch controls.'),
  p(33,'WarmFlow Smart Bottle Warmer','Baby Tech',1399,'SMART HEAT',pics.steriliser,'Precision bottle warming with temperature presets and keep-warm mode.'),
  p(34,'Hush Mini White Noise Machine','Baby Tech',1299,'SLEEP',pics.monitor,'Rechargeable sleep sound machine with night light, timer and calming sounds.'),
  p(35,'NestSense Room Sensor','Baby Tech',2499,'SENSOR',pics.monitor,'Tracks nursery temperature and humidity for a more comfortable sleep environment.'),
  p(36,'Breathe Smart Humidifier','Baby Tech',2199,'AIR CARE',pics.monitor,'Quiet nursery humidifier with adjustable mist and automatic shut-off.'),
  p(37,'Glow Smart Night Light','Baby Tech',999,'NIGHT',pics.monitor,'Touch-controlled nursery light with dimming, timer and soft bedtime glow.'),
  p(38,'TempCheck Digital Thermometer','Baby Tech',899,'HEALTH',pics.monitor,'Fast digital temperature readings with a simple illuminated display.'),
  p(39,'SleepView Wi-Fi Camera','Baby Tech',3499,'WI-FI',pics.monitor,'App-connected nursery camera with HD video, motion alerts and two-way audio.'),
  p(40,'PureAir Nursery Monitor','Baby Tech',2799,'AIR SENSOR',pics.monitor,'Smart air-quality monitor tracking temperature, humidity and nursery comfort.'),

  p(41,'Maison Premium High Chair','Feeding',3899,'DESIGN',pics.highchair,'Easy-clean premium high chair with adjustable footrest and removable tray.'),
  p(42,'GrowWithMe High Chair','Feeding',4499,'GROW',pics.highchair,'Convertible high chair that adapts as your baby grows into toddlerhood.'),
  p(43,'Nordic Wood High Chair','Feeding',5299,'PREMIUM',pics.highchair,'Scandinavian-inspired feeding chair with a warm wood finish and secure harness.'),
  p(44,'FoldAway Feeding Chair','Feeding',2999,'COMPACT',pics.highchair,'Space-saving folding high chair for smaller homes and easy storage.'),
  p(45,'EasyClean Luxe Chair','Feeding',3599,'EASY CLEAN',pics.highchair,'Wipe-clean premium seat with removable tray and adjustable recline.'),
  p(46,'Mini Table Booster','Feeding',1499,'BOOSTER',pics.highchair,'Portable booster seat for family meals at home or while travelling.'),
  p(47,'Comfort Recline High Chair','Feeding',4199,'RECLINE',pics.highchair,'Multi-position feeding chair with padded support for younger babies.'),
  p(48,'Studio Minimal High Chair','Feeding',4799,'DESIGN',pics.highchair,'Minimal premium chair designed to complement modern dining spaces.'),
  p(49,'TwinTray Feeding Station','Feeding',3299,'PRACTICAL',pics.highchair,'Functional high chair with removable double tray and adjustable height.'),
  p(50,'Signature Dining Chair','Feeding',5999,'LUXE',pics.highchair,'Luxury feeding chair with refined materials and long-term convertible use.'),

  p(51,'Aura Ergonomic Baby Carrier','On The Go',2499,'ERGONOMIC',pics.carrier,'Structured carrier with breathable panels, lumbar support and multiple positions.'),
  p(52,'AirMesh Newborn Carrier','On The Go',1999,'BREATHABLE',pics.carrier,'Lightweight mesh carrier designed for close, comfortable newborn carrying.'),
  p(53,'Explorer Hiking Carrier','On The Go',4499,'ADVENTURE',pics.carrier,'Supportive child carrier with storage and structured frame for family adventures.'),
  p(54,'City Sling Carrier','On The Go',1299,'LIGHT',pics.carrier,'Soft everyday sling for quick errands and close carrying.'),
  p(55,'FlexFit 4-Way Carrier','On The Go',2899,'4-WAY',pics.carrier,'Adjustable carrier supporting multiple front and back carry positions.'),
  p(56,'Travel Changing Backpack','On The Go',2199,'TRAVEL',pics.carrier,'Premium changing backpack with insulated pockets and organised baby storage.'),
  p(57,'Pram Organiser Luxe','On The Go',999,'ORGANISER',pics.carrier,'Structured pram organiser for bottles, phone, keys and daily essentials.'),
  p(58,'Portable Changing Mat','On The Go',799,'ESSENTIAL',pics.carrier,'Foldable padded changing mat designed for clean changes anywhere.'),
  p(59,'Thermal Bottle Travel Bag','On The Go',899,'INSULATED',pics.carrier,'Insulated travel bag that helps maintain bottle temperature while out.'),
  p(60,'All-Day Parent Backpack','On The Go',2799,'PREMIUM',pics.carrier,'Spacious premium baby backpack with changing storage and laptop compartment.')
]

export const categories = ['All', 'Prams & Travel Systems', 'Car Seats', 'Nursery', 'Baby Tech', 'Feeding', 'On The Go']
